FROM nginx:1.22.1

# Copy custom configuration file from the current directory
COPY /nginx/conf/default.conf /etc/nginx/conf.d/default.conf

# Install dependencies
RUN apt-get update && apt-get install -y \
    curl \
    git \
    unzip \
    vim \
    wget \
    zip \
    nano \
    nmap \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /var/www/html

# Copy existing application directory contents
COPY /app/app /var/www/html

# Expose ports
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
